dist: bionic
services:
  - memcached
  - redis
language: python
python:
  - "3.6"
  - "3.7"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
jobs:
  allow_failures:
    # Sometimes nightly builds are broken, or contain breaking changes that affect dependencies we have
    # no control over. Thus we don't want a failed nightly run to cause Travis to consider the build broken.
    - python: 'nightly'
    - python: '3.9'
install:
  - if python --version | grep -q "Python 3.6"; then
    pip install dataclasses;
    fi
  - pip install '.[dev]'
script: pytest --cov=./privex -rxXs -v
after_success:
  - codecov